app = "star-premium-bot"  # Fly.io dagi app nomi

[build]

[env]
  # Environment o'zgaruvchilar secret sifatida saqlanadi

[[services]]
  internal_port = 8080
  protocol = "tcp"
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]
  
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]